import type { QuizQuestion } from "./types";

export const QUESTIONS: QuizQuestion[] = [
  // ───────── Application Layer ─────────
  {
    id: "app-01",
    category: "application",
    difficulty: "easy",
    prompt: "Which protocol resolves a domain name to an IP address?",
    options: ["DHCP", "DNS", "ARP", "SMTP"],
    answer: 1,
    explanation: "DNS (Domain Name System) maps human-readable names to IP addresses.",
  },
  {
    id: "app-02",
    category: "application",
    difficulty: "easy",
    prompt: "HTTP runs by default on port…",
    options: ["21", "22", "80", "443"],
    answer: 2,
    explanation: "HTTP uses port 80; HTTPS uses 443.",
  },
  {
    id: "app-03",
    category: "application",
    difficulty: "easy",
    prompt: "Which is a stateful, command-response email submission protocol?",
    options: ["POP3", "IMAP", "SMTP", "DNS"],
    answer: 2,
    explanation: "SMTP submits/relays mail with HELO/EHLO, MAIL FROM, RCPT TO, DATA commands.",
  },
  {
    id: "app-04",
    category: "application",
    difficulty: "medium",
    prompt: "What does HTTP/2 add over HTTP/1.1 to reduce head-of-line blocking?",
    options: [
      "Server push only",
      "Binary framing with multiplexed streams",
      "TLS by default",
      "JSON-only payloads",
    ],
    answer: 1,
    explanation: "HTTP/2 multiplexes multiple streams over a single TCP connection.",
  },
  {
    id: "app-05",
    category: "application",
    difficulty: "easy",
    prompt: "An iterative DNS query expects each server to…",
    options: [
      "Return either the answer or a referral",
      "Recursively ask other servers and return only the final answer",
      "Always cache for 24 hours",
      "Forward to root only",
    ],
    answer: 0,
    explanation: "Iterative queries get either an answer or a referral; recursion is the resolver's job.",
  },
  {
    id: "app-06",
    category: "application",
    difficulty: "medium",
    prompt: "DASH adaptive streaming switches between bitrate variants based on…",
    options: [
      "Disk space at the server",
      "Per-segment client measurements of throughput",
      "User's IP address geography only",
      "TLS handshake duration",
    ],
    answer: 1,
    explanation: "Clients measure their throughput per segment and pick a manifest variant.",
  },
  {
    id: "app-07",
    category: "application",
    difficulty: "medium",
    prompt: "In BitTorrent, the rarest-first chunk strategy primarily…",
    options: [
      "Reduces server load only",
      "Maximizes the number of chunks available across the swarm",
      "Encrypts the torrent",
      "Is required by the protocol spec",
    ],
    answer: 1,
    explanation: "Rarest-first improves swarm health by spreading scarce chunks faster.",
  },
  {
    id: "app-08",
    category: "application",
    difficulty: "medium",
    prompt: "A persistent HTTP connection differs from non-persistent in that…",
    options: [
      "Each object opens a new TCP connection",
      "All objects can reuse a single TCP connection",
      "It mandates TLS",
      "It is HTTP/3-only",
    ],
    answer: 1,
    explanation: "Persistent connections (default in HTTP/1.1) reuse a TCP connection across requests.",
  },
  {
    id: "app-09",
    category: "application",
    difficulty: "hard",
    prompt: "Which HTTP header signals a cache that responses must be revalidated?",
    options: ["X-Forwarded-For", "ETag", "Cache-Control: no-cache", "Connection: keep-alive"],
    answer: 2,
    explanation:
      "Cache-Control: no-cache requires revalidation with the origin before reuse. ETag enables that revalidation.",
  },
  {
    id: "app-10",
    category: "application",
    difficulty: "hard",
    prompt: "DNS over HTTPS (DoH) primarily protects what property of a query?",
    options: ["Latency", "Authenticity only", "Confidentiality from on-path observers", "TTL"],
    answer: 2,
    explanation: "DoH encrypts the DNS query with TLS, hiding it from on-path observers.",
  },
  {
    id: "app-11",
    category: "application",
    difficulty: "easy",
    prompt: "Sockets at the application layer are addressed by…",
    options: ["MAC + IP", "IP + port", "URL only", "MAC only"],
    answer: 1,
    explanation: "An endpoint is uniquely identified by (IP, port).",
  },
  {
    id: "app-12",
    category: "application",
    difficulty: "easy",
    prompt: "DNS records of type 'MX' specify…",
    options: [
      "Mail exchanger hosts for a domain",
      "Mobile IP exchange",
      "Multicast extension",
      "Master mode",
    ],
    answer: 0,
    explanation: "MX records advertise the mail server(s) responsible for receiving mail for a domain.",
  },
  {
    id: "app-13",
    category: "application",
    difficulty: "medium",
    prompt: "REST APIs are typically built on top of which protocol?",
    options: ["FTP", "HTTP", "SNMP", "ICMP"],
    answer: 1,
    explanation: "REST uses HTTP verbs and status codes as transport semantics.",
  },
  {
    id: "app-14",
    category: "application",
    difficulty: "medium",
    prompt: "WebSocket upgrades from HTTP using which header?",
    options: ["Connection: Upgrade", "Sec-Cookie", "Server: WS", "Authorization: Bearer"],
    answer: 0,
    explanation: "The upgrade handshake includes 'Connection: Upgrade' and 'Upgrade: websocket'.",
  },
  {
    id: "app-15",
    category: "application",
    difficulty: "hard",
    prompt: "Which DNS feature allows multiple A records for the same name to be returned in different orders for load balancing?",
    options: ["Round-robin DNS", "DNSSEC", "Recursive resolution", "EDNS"],
    answer: 0,
    explanation: "Round-robin DNS rotates record order in responses to spread load.",
  },
  {
    id: "app-16",
    category: "application",
    difficulty: "easy",
    prompt: "Which protocol is best for live, latency-sensitive voice (VoIP)?",
    options: ["TCP-only", "UDP-based RTP", "FTP", "SMTP"],
    answer: 1,
    explanation: "Real-time media uses UDP+RTP for lower latency over reliability.",
  },
  {
    id: "app-17",
    category: "application",
    difficulty: "medium",
    prompt: "A CDN improves performance primarily by…",
    options: [
      "Caching content closer to users",
      "Compressing TCP segments",
      "Skipping DNS resolution",
      "Decreasing TTL",
    ],
    answer: 0,
    explanation: "CDNs replicate content to edge locations near users.",
  },
  {
    id: "app-18",
    category: "application",
    difficulty: "medium",
    prompt: "QUIC, the transport beneath HTTP/3, is built on top of…",
    options: ["TCP", "UDP", "ICMP", "ARP"],
    answer: 1,
    explanation: "QUIC runs over UDP and implements its own reliability and TLS-like crypto.",
  },
  {
    id: "app-19",
    category: "application",
    difficulty: "hard",
    prompt: "An HTTP redirect with status 308 differs from 301 in that 308…",
    options: [
      "Preserves the original request method",
      "Is temporary",
      "Is HTTPS-only",
      "Cannot be cached",
    ],
    answer: 0,
    explanation: "308 is a permanent redirect that preserves method (POST stays POST), unlike 301.",
  },
  {
    id: "app-20",
    category: "application",
    difficulty: "easy",
    prompt: "DHCP DISCOVER is sent to which destination IP?",
    options: ["0.0.0.0", "127.0.0.1", "255.255.255.255", "224.0.0.1"],
    answer: 2,
    explanation: "DHCP DISCOVER is broadcast to 255.255.255.255 because the client has no IP yet.",
  },

  // ───────── Transport Layer ─────────
  {
    id: "trans-01",
    category: "transport",
    difficulty: "easy",
    prompt: "Which transport protocol provides reliability and ordered delivery?",
    options: ["UDP", "TCP", "ICMP", "ARP"],
    answer: 1,
    explanation: "TCP provides reliability via acks/retransmits; UDP does not.",
  },
  {
    id: "trans-02",
    category: "transport",
    difficulty: "easy",
    prompt: "A TCP segment header carries which two port numbers?",
    options: ["MAC and IP", "Source and destination", "ASN and prefix", "VLAN and PCP"],
    answer: 1,
    explanation: "Source port and destination port identify endpoints at the transport layer.",
  },
  {
    id: "trans-03",
    category: "transport",
    difficulty: "easy",
    prompt: "TCP's three-way handshake is…",
    options: ["SYN → ACK → FIN", "SYN → SYN+ACK → ACK", "FIN → SYN → ACK", "GET → 200 → BYE"],
    answer: 1,
    explanation: "Client SYN, server SYN+ACK, client ACK — three messages, both ISNs agreed.",
  },
  {
    id: "trans-04",
    category: "transport",
    difficulty: "medium",
    prompt: "TCP fast retransmit triggers after receiving how many duplicate ACKs?",
    options: ["1", "2", "3", "4"],
    answer: 2,
    explanation: "Three duplicate ACKs is the canonical fast-retransmit trigger.",
  },
  {
    id: "trans-05",
    category: "transport",
    difficulty: "medium",
    prompt: "The TCP receive window primarily implements…",
    options: ["Congestion control", "Flow control", "Routing", "Encryption"],
    answer: 1,
    explanation: "rwnd is flow control: the receiver tells the sender how much it can buffer.",
  },
  {
    id: "trans-06",
    category: "transport",
    difficulty: "medium",
    prompt: "TCP Reno's response to a 3-dupACK loss is to…",
    options: [
      "Reset cwnd to 1 MSS",
      "Halve cwnd and continue",
      "Double cwnd",
      "Disconnect",
    ],
    answer: 1,
    explanation: "Reno halves cwnd (multiplicative decrease) and avoids slow-start on fast retransmit.",
  },
  {
    id: "trans-07",
    category: "transport",
    difficulty: "easy",
    prompt: "UDP is preferred over TCP when…",
    options: [
      "Reliability is critical",
      "Low latency matters more than reliability",
      "We need congestion control",
      "Ports are exhausted",
    ],
    answer: 1,
    explanation: "DNS, RTP, and similar use UDP because added TCP latency hurts more than loss.",
  },
  {
    id: "trans-08",
    category: "transport",
    difficulty: "medium",
    prompt: "Slow start ends and congestion avoidance begins at…",
    options: [
      "ssthresh",
      "rwnd",
      "MSS",
      "TTL=0",
    ],
    answer: 0,
    explanation: "When cwnd reaches ssthresh, the sender shifts to AIMD growth.",
  },
  {
    id: "trans-09",
    category: "transport",
    difficulty: "hard",
    prompt: "Nagle's algorithm aims to reduce…",
    options: [
      "Tinygram (small packet) overhead",
      "Out-of-order delivery",
      "Retransmissions only",
      "Header size",
    ],
    answer: 0,
    explanation: "Nagle batches small writes until ACKs arrive to avoid 41-byte packets carrying 1 byte.",
  },
  {
    id: "trans-10",
    category: "transport",
    difficulty: "easy",
    prompt: "TCP's MSS is…",
    options: [
      "Maximum Segment Size",
      "Multi-Stream Sequence",
      "Minimum SYN size",
      "Master Socket",
    ],
    answer: 0,
    explanation: "MSS is the largest payload (excluding headers) a TCP segment can carry.",
  },
  {
    id: "trans-11",
    category: "transport",
    difficulty: "medium",
    prompt: "Which is true about UDP checksum?",
    options: [
      "Mandatory in IPv4 only",
      "Optional in IPv4, mandatory in IPv6",
      "Always disabled",
      "Identical to IP checksum",
    ],
    answer: 1,
    explanation: "UDP checksum is optional under IPv4 but required under IPv6.",
  },
  {
    id: "trans-12",
    category: "transport",
    difficulty: "medium",
    prompt: "Selective acknowledgments (SACK) help TCP by…",
    options: [
      "Acknowledging non-contiguous data ranges",
      "Encrypting payload",
      "Compressing headers",
      "Resolving DNS",
    ],
    answer: 0,
    explanation: "SACK lets a receiver tell the sender precisely which bytes it has, beyond cumulative ACK.",
  },
  {
    id: "trans-13",
    category: "transport",
    difficulty: "hard",
    prompt: "TCP CUBIC differs from Reno mainly by…",
    options: [
      "Using a cubic function of time since last loss for window growth",
      "Using fixed AIMD only",
      "Switching to UDP",
      "Disabling slow start",
    ],
    answer: 0,
    explanation: "CUBIC scales cwnd as a cubic function of time since the last congestion event, scaling better on long fat networks.",
  },
  {
    id: "trans-14",
    category: "transport",
    difficulty: "easy",
    prompt: "FIN flag in TCP indicates…",
    options: [
      "Forced reset",
      "End of data from this side",
      "Fragmentation needed",
      "Final routing hop",
    ],
    answer: 1,
    explanation: "FIN signals the sender has no more data; it's part of graceful close.",
  },
  {
    id: "trans-15",
    category: "transport",
    difficulty: "medium",
    prompt: "Which is NOT a feature of QUIC?",
    options: [
      "0-RTT connection resumption",
      "Stream multiplexing without HoL blocking across streams",
      "Header compression",
      "Built on top of TCP",
    ],
    answer: 3,
    explanation: "QUIC runs on UDP, not TCP — that's a core design choice.",
  },
  {
    id: "trans-16",
    category: "transport",
    difficulty: "hard",
    prompt: "Bufferbloat causes high latency because…",
    options: [
      "Excessively large queues delay packets even when there is no loss",
      "TCP retransmits too often",
      "Cables are too long",
      "Receivers ignore ACKs",
    ],
    answer: 0,
    explanation: "Oversized queues hold packets, raising RTT and confusing TCP's loss-based congestion control.",
  },
  {
    id: "trans-17",
    category: "transport",
    difficulty: "medium",
    prompt: "MPTCP enables a single connection to use…",
    options: [
      "Multiple TCP subflows over different paths",
      "UDP fallback",
      "Multicast",
      "Out-of-order DNS",
    ],
    answer: 0,
    explanation: "Multipath TCP runs subflows over multiple interfaces (e.g., Wi-Fi + cellular).",
  },
  {
    id: "trans-18",
    category: "transport",
    difficulty: "easy",
    prompt: "TCP segment 'PSH' flag asks the receiver to…",
    options: [
      "Push buffered data to the application immediately",
      "Push state to a peer",
      "Skip retransmissions",
      "Print segment to log",
    ],
    answer: 0,
    explanation: "PSH is a hint to deliver buffered bytes to the application without waiting for the buffer to fill.",
  },
  {
    id: "trans-19",
    category: "transport",
    difficulty: "hard",
    prompt: "TIME_WAIT exists primarily to…",
    options: [
      "Allow late duplicate segments to expire and protect a new incarnation of the same 4-tuple",
      "Save energy",
      "Negotiate TLS",
      "Drop bad routes",
    ],
    answer: 0,
    explanation: "TIME_WAIT prevents a delayed segment from being misinterpreted by a new connection on the same 4-tuple.",
  },
  {
    id: "trans-20",
    category: "transport",
    difficulty: "easy",
    prompt: "Which port range is reserved for well-known services?",
    options: ["0–1023", "1024–49151", "49152–65535", "65536+"],
    answer: 0,
    explanation: "Ports 0–1023 are well-known and typically require privilege to bind.",
  },

  // ───────── Network Layer ─────────
  {
    id: "net-01",
    category: "network",
    difficulty: "easy",
    prompt: "An IPv4 address has how many bits?",
    options: ["16", "32", "48", "128"],
    answer: 1,
    explanation: "IPv4 = 32 bits, IPv6 = 128 bits.",
  },
  {
    id: "net-02",
    category: "network",
    difficulty: "easy",
    prompt: "TTL in IPv4 is decremented by…",
    options: ["Switches", "Routers", "End hosts only", "DHCP servers"],
    answer: 1,
    explanation: "Each forwarding router decrements TTL by 1; reaching 0 triggers ICMP Time Exceeded.",
  },
  {
    id: "net-03",
    category: "network",
    difficulty: "easy",
    prompt: "Which is a CIDR block?",
    options: ["10.0.0.0", "10.0.0.0/24", "10/8/24", "10.0.0.0:80"],
    answer: 1,
    explanation: "CIDR is base/prefix-length, e.g., 10.0.0.0/24.",
  },
  {
    id: "net-04",
    category: "network",
    difficulty: "easy",
    prompt: "RFC1918 private addresses include…",
    options: ["8.8.8.0/24", "192.168.0.0/16", "1.1.1.0/24", "169.254.0.0/16 only"],
    answer: 1,
    explanation: "10/8, 172.16/12, and 192.168/16 are private (RFC1918). 169.254/16 is link-local (RFC3927).",
  },
  {
    id: "net-05",
    category: "network",
    difficulty: "medium",
    prompt: "NAT primarily translates which fields?",
    options: [
      "MAC addresses",
      "IPs (and often ports) between private and public realms",
      "URLs",
      "DNS records",
    ],
    answer: 1,
    explanation: "Most home NATs are NAPT/PAT and translate IP+port pairs.",
  },
  {
    id: "net-06",
    category: "network",
    difficulty: "medium",
    prompt: "OSPF is which kind of routing protocol?",
    options: [
      "Distance-vector exterior",
      "Link-state interior",
      "Path-vector exterior",
      "Static only",
    ],
    answer: 1,
    explanation: "OSPF is a link-state IGP — each router floods LSAs and computes Dijkstra.",
  },
  {
    id: "net-07",
    category: "network",
    difficulty: "medium",
    prompt: "BGP is best characterized as…",
    options: [
      "An interior gateway protocol",
      "A path-vector exterior gateway protocol",
      "A link-state EGP",
      "A static intra-domain protocol",
    ],
    answer: 1,
    explanation: "BGP carries AS_PATH and is the de-facto inter-domain routing protocol of the Internet.",
  },
  {
    id: "net-08",
    category: "network",
    difficulty: "easy",
    prompt: "The default subnet mask for a /24 prefix is…",
    options: ["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.255"],
    answer: 2,
    explanation: "/24 = 24 ones followed by 8 zeros = 255.255.255.0.",
  },
  {
    id: "net-09",
    category: "network",
    difficulty: "hard",
    prompt: "How many usable hosts in a /27 subnet?",
    options: ["32", "30", "62", "14"],
    answer: 1,
    explanation: "/27 → 32 addresses minus network and broadcast = 30 usable.",
  },
  {
    id: "net-10",
    category: "network",
    difficulty: "easy",
    prompt: "ICMP echo request/reply is used by…",
    options: ["traceroute only", "ping", "DNS recursion", "DHCP DISCOVER"],
    answer: 1,
    explanation: "ping uses ICMP Echo (type 8 request, type 0 reply).",
  },
  {
    id: "net-11",
    category: "network",
    difficulty: "medium",
    prompt: "IPv6 SLAAC obtains an address by…",
    options: [
      "Asking a DHCP server",
      "Combining a router-advertised prefix with an interface identifier",
      "Querying DNS",
      "Reading an Ethernet broadcast",
    ],
    answer: 1,
    explanation: "Stateless Address Autoconfiguration uses RA prefixes + interface ID (often EUI-64 or random).",
  },
  {
    id: "net-12",
    category: "network",
    difficulty: "medium",
    prompt: "Which best describes longest-prefix matching?",
    options: [
      "Pick the route with the largest hop count",
      "Pick the route whose prefix length covers the destination most specifically",
      "Choose the lowest IP",
      "Prefer EBGP over IBGP",
    ],
    answer: 1,
    explanation: "Forwarding tables are searched for the most specific prefix match.",
  },
  {
    id: "net-13",
    category: "network",
    difficulty: "easy",
    prompt: "A traceroute typically works by…",
    options: [
      "Sending TCP RST",
      "Sending packets with increasing TTLs and capturing ICMP Time Exceeded",
      "Asking DNS",
      "Running BGP",
    ],
    answer: 1,
    explanation: "Each TTL=N packet expires at the Nth router, which returns ICMP Time Exceeded.",
  },
  {
    id: "net-14",
    category: "network",
    difficulty: "medium",
    prompt: "An SDN data plane is typically configured by…",
    options: [
      "Manual ARP",
      "A logically centralized controller pushing flow rules",
      "OSPF only",
      "DNS",
    ],
    answer: 1,
    explanation: "SDN separates control and data planes: a controller programs forwarding behavior into switches via APIs like OpenFlow.",
  },
  {
    id: "net-15",
    category: "network",
    difficulty: "medium",
    prompt: "Which header field signals fragmentation in IPv4?",
    options: ["TTL only", "Flags + Fragment Offset", "Protocol", "Checksum"],
    answer: 1,
    explanation: "DF/MF flags and the Fragment Offset implement IPv4 fragmentation.",
  },
  {
    id: "net-16",
    category: "network",
    difficulty: "hard",
    prompt: "Anycast routing delivers a packet to…",
    options: [
      "All hosts in a group",
      "Any one of the hosts in a group, typically the topologically closest",
      "Exactly one specified host",
      "A random host on Earth",
    ],
    answer: 1,
    explanation: "Anycast advertises the same prefix from many sites; routing picks the closest.",
  },
  {
    id: "net-17",
    category: "network",
    difficulty: "easy",
    prompt: "Which IP address is loopback?",
    options: ["10.0.0.1", "127.0.0.1", "192.168.0.1", "8.8.8.8"],
    answer: 1,
    explanation: "127.0.0.0/8 is loopback; 127.0.0.1 is the canonical address.",
  },
  {
    id: "net-18",
    category: "network",
    difficulty: "medium",
    prompt: "RIP uses which metric?",
    options: ["Hop count, capped at 15", "Bandwidth-delay", "AS_PATH length", "Latency"],
    answer: 0,
    explanation: "RIP is distance-vector with a 15-hop limit (16 = infinity).",
  },
  {
    id: "net-19",
    category: "network",
    difficulty: "hard",
    prompt: "ECMP allows a router to…",
    options: [
      "Drop all but one route to avoid loops",
      "Spread traffic across multiple paths of equal cost",
      "Choose the worst path for testing",
      "Aggregate prefixes only",
    ],
    answer: 1,
    explanation: "Equal-Cost Multi-Path balances flows across multiple equally good next hops.",
  },
  {
    id: "net-20",
    category: "network",
    difficulty: "easy",
    prompt: "A default gateway is…",
    options: [
      "A DNS resolver",
      "The router used when no specific route matches",
      "A switch",
      "A firewall always",
    ],
    answer: 1,
    explanation: "When no longer-prefix match exists, the host sends to the default gateway (0.0.0.0/0).",
  },

  // ───────── Link Layer & LANs ─────────
  {
    id: "link-01",
    category: "link",
    difficulty: "easy",
    prompt: "A MAC address has how many bits?",
    options: ["16", "32", "48", "64"],
    answer: 2,
    explanation: "Standard EUI-48 MAC addresses are 48 bits long.",
  },
  {
    id: "link-02",
    category: "link",
    difficulty: "easy",
    prompt: "ARP maps…",
    options: ["IP → MAC", "MAC → IP", "URL → IP", "Port → MAC"],
    answer: 0,
    explanation: "Address Resolution Protocol resolves an IPv4 address to a MAC address on the same LAN.",
  },
  {
    id: "link-03",
    category: "link",
    difficulty: "easy",
    prompt: "Ethernet uses what to detect bit errors?",
    options: ["Parity bit only", "CRC-32 (FCS)", "MD5", "TLS"],
    answer: 1,
    explanation: "The Frame Check Sequence is a CRC-32 over the frame.",
  },
  {
    id: "link-04",
    category: "link",
    difficulty: "medium",
    prompt: "An Ethernet switch builds its forwarding table by…",
    options: [
      "Reading DHCP leases",
      "Learning source MAC addresses on incoming ports",
      "Static config only",
      "BGP advertisements",
    ],
    answer: 1,
    explanation: "Switches learn (port, source-MAC) bindings as they observe frames.",
  },
  {
    id: "link-05",
    category: "link",
    difficulty: "medium",
    prompt: "STP exists to…",
    options: ["Speed up routing", "Prevent broadcast loops in bridged LANs", "Replace ARP", "Encrypt frames"],
    answer: 1,
    explanation: "Spanning Tree Protocol blocks ports to break loops at L2.",
  },
  {
    id: "link-06",
    category: "link",
    difficulty: "easy",
    prompt: "Which is a VLAN tag standard?",
    options: ["802.1X", "802.1Q", "802.3ad", "802.11ac"],
    answer: 1,
    explanation: "802.1Q defines VLAN tagging for Ethernet frames.",
  },
  {
    id: "link-07",
    category: "link",
    difficulty: "medium",
    prompt: "Wi-Fi (802.11) MAC uses…",
    options: ["CSMA/CD", "CSMA/CA", "Token passing", "TDMA only"],
    answer: 1,
    explanation: "Wireless can't reliably detect collisions, so 802.11 uses Collision Avoidance.",
  },
  {
    id: "link-08",
    category: "link",
    difficulty: "easy",
    prompt: "What is the broadcast MAC address?",
    options: [
      "FF:FF:FF:FF:FF:FF",
      "00:00:00:00:00:00",
      "01:00:5E:00:00:01",
      "AA:BB:CC:DD:EE:FF",
    ],
    answer: 0,
    explanation: "All-ones MAC is the L2 broadcast address.",
  },
  {
    id: "link-09",
    category: "link",
    difficulty: "medium",
    prompt: "Hubs differ from switches because hubs…",
    options: [
      "Forward only on the destination port",
      "Repeat every frame to every port (collision domain shared)",
      "Operate at L3",
      "Are programmable via APIs",
    ],
    answer: 1,
    explanation: "A hub is a dumb repeater; all ports share one collision domain.",
  },
  {
    id: "link-10",
    category: "link",
    difficulty: "hard",
    prompt: "PoE delivers power over Ethernet using…",
    options: [
      "Separate AC outlet",
      "Spare or signal pairs of the twisted-pair cable",
      "USB connector",
      "Coaxial only",
    ],
    answer: 1,
    explanation: "Power over Ethernet injects DC over the same twisted pairs (or spares).",
  },
  {
    id: "link-11",
    category: "link",
    difficulty: "easy",
    prompt: "An Ethernet frame's EtherType 0x0800 means the payload is…",
    options: ["IPv6", "IPv4", "ARP", "MPLS"],
    answer: 1,
    explanation: "0x0800 = IPv4. ARP = 0x0806, IPv6 = 0x86DD.",
  },
  {
    id: "link-12",
    category: "link",
    difficulty: "medium",
    prompt: "A LAN's broadcast domain is bounded by…",
    options: ["A hub", "A switch", "A router", "A repeater"],
    answer: 2,
    explanation: "Routers do not forward L2 broadcasts; switches/hubs do.",
  },
  {
    id: "link-13",
    category: "link",
    difficulty: "easy",
    prompt: "Wi-Fi 6 corresponds to which IEEE standard?",
    options: ["802.11n", "802.11ac", "802.11ax", "802.11g"],
    answer: 2,
    explanation: "Wi-Fi 6 = 802.11ax.",
  },
  {
    id: "link-14",
    category: "link",
    difficulty: "medium",
    prompt: "A trunk port carries…",
    options: ["A single VLAN only", "Multiple VLANs with 802.1Q tags", "Storage traffic only", "Voice only"],
    answer: 1,
    explanation: "Trunk ports tag frames so multiple VLANs share one link.",
  },
  {
    id: "link-15",
    category: "link",
    difficulty: "hard",
    prompt: "Gratuitous ARP is used to…",
    options: [
      "Detect duplicate IP / announce a fresh IP-to-MAC binding",
      "Send a frame with no payload",
      "Encrypt L2",
      "Replace DHCP",
    ],
    answer: 0,
    explanation: "A host can announce its IP/MAC mapping without a request — used by failover and duplicate detection.",
  },
  {
    id: "link-16",
    category: "link",
    difficulty: "medium",
    prompt: "Link aggregation (LACP) provides…",
    options: ["Encryption", "Higher throughput and link redundancy by bonding ports", "Routing", "Wireless QoS"],
    answer: 1,
    explanation: "LACP/802.3ad bonds multiple links between two devices into one logical link.",
  },
  {
    id: "link-17",
    category: "link",
    difficulty: "easy",
    prompt: "Cat 6 cable typically supports…",
    options: ["10 Mbps", "100 Mbps", "1 Gbps (and 10 Gbps for short distances)", "100 Gbps"],
    answer: 2,
    explanation: "Cat 6 supports up to 10GBASE-T over short runs; Cat 6A is engineered for full 100m.",
  },
  {
    id: "link-18",
    category: "link",
    difficulty: "medium",
    prompt: "An access point in 802.11 infrastructure mode…",
    options: [
      "Bridges wireless STAs to a wired LAN",
      "Acts as a router",
      "Is purely a DHCP server",
      "Operates at L7",
    ],
    answer: 0,
    explanation: "An AP is an L2 bridge between Wi-Fi clients and the wired distribution system.",
  },
  {
    id: "link-19",
    category: "link",
    difficulty: "hard",
    prompt: "BPDU guard on a switch protects against…",
    options: [
      "Rogue switches injecting BPDUs and altering the spanning tree",
      "DHCP starvation",
      "MAC flooding",
      "ARP spoofing",
    ],
    answer: 0,
    explanation: "BPDU guard error-disables a port if it sees a BPDU on an access port.",
  },
  {
    id: "link-20",
    category: "link",
    difficulty: "easy",
    prompt: "An Ethernet preamble is used for…",
    options: [
      "Clock synchronization between sender and receiver",
      "Encryption",
      "Compression",
      "Routing",
    ],
    answer: 0,
    explanation: "The 7-byte preamble + SFD synchronizes the receiver's clock to the sender's bit timing.",
  },

  // ───────── Cybersecurity & Cryptography ─────────
  {
    id: "sec-01",
    category: "security",
    difficulty: "easy",
    prompt: "Which is a symmetric cipher?",
    options: ["RSA", "ECDSA", "AES", "DSA"],
    answer: 2,
    explanation: "AES uses one secret key for both encrypt and decrypt — symmetric.",
  },
  {
    id: "sec-02",
    category: "security",
    difficulty: "easy",
    prompt: "TLS protects which property of a connection?",
    options: ["Latency only", "Confidentiality, integrity, and authenticity", "Compression only", "Routing"],
    answer: 1,
    explanation: "TLS provides CIA + identity via certificates.",
  },
  {
    id: "sec-03",
    category: "security",
    difficulty: "easy",
    prompt: "A digital certificate binds a public key to…",
    options: ["A MAC address", "A DNS TTL", "An identity (name, domain)", "An IP only"],
    answer: 2,
    explanation: "Certificates assert that a given public key belongs to a named subject, signed by a CA.",
  },
  {
    id: "sec-04",
    category: "security",
    difficulty: "medium",
    prompt: "Diffie-Hellman provides…",
    options: [
      "Authentication",
      "Key agreement over an insecure channel",
      "Hashing",
      "Compression",
    ],
    answer: 1,
    explanation: "DH lets two parties derive a shared secret without ever transmitting it.",
  },
  {
    id: "sec-05",
    category: "security",
    difficulty: "medium",
    prompt: "Forward secrecy means…",
    options: [
      "Each session uses ephemeral keys; future leaks of long-term keys do not decrypt past sessions",
      "All traffic is logged forward",
      "The server uses only one key forever",
      "Clients reuse keys",
    ],
    answer: 0,
    explanation: "PFS uses ephemeral DH keys per session, so compromise later doesn't decrypt past sessions.",
  },
  {
    id: "sec-06",
    category: "security",
    difficulty: "easy",
    prompt: "SHA-256 outputs how many bits?",
    options: ["128", "192", "256", "512"],
    answer: 2,
    explanation: "256-bit (32 bytes) digest.",
  },
  {
    id: "sec-07",
    category: "security",
    difficulty: "easy",
    prompt: "Which is a network firewall function?",
    options: [
      "Encrypting traffic",
      "Filtering packets/connections by rules",
      "Routing only",
      "DNS resolution",
    ],
    answer: 1,
    explanation: "Firewalls match rules (allow/deny) on flows; some also do NAT or DPI.",
  },
  {
    id: "sec-08",
    category: "security",
    difficulty: "medium",
    prompt: "An IDS is best described as…",
    options: [
      "An intrusion detection system that observes and alerts",
      "An inline filter that blocks",
      "A DNS resolver",
      "A VPN",
    ],
    answer: 0,
    explanation: "An IDS observes (typically a tap/span) and alerts. An IPS is inline and can block.",
  },
  {
    id: "sec-09",
    category: "security",
    difficulty: "medium",
    prompt: "DNSSEC primarily provides…",
    options: ["Confidentiality", "Authenticity and integrity of DNS responses", "Caching", "Compression"],
    answer: 1,
    explanation: "DNSSEC signs records — clients can verify they were not tampered. It does NOT encrypt queries.",
  },
  {
    id: "sec-10",
    category: "security",
    difficulty: "hard",
    prompt: "Which attack tricks a switch into flooding by exhausting its CAM table?",
    options: ["ARP poisoning", "MAC flooding", "Smurf attack", "ICMP redirect"],
    answer: 1,
    explanation: "Filling the CAM/MAC table forces the switch to behave like a hub for unknown MACs.",
  },
  {
    id: "sec-11",
    category: "security",
    difficulty: "easy",
    prompt: "A salted password hash adds…",
    options: [
      "Per-user random data to defeat precomputed (rainbow) tables",
      "Compression",
      "TLS support",
      "Caching",
    ],
    answer: 0,
    explanation: "Salt makes equal passwords hash differently per user, breaking rainbow tables.",
  },
  {
    id: "sec-12",
    category: "security",
    difficulty: "medium",
    prompt: "HMAC provides…",
    options: [
      "Confidentiality only",
      "Message authentication and integrity using a shared key",
      "Public-key signatures",
      "Compression",
    ],
    answer: 1,
    explanation: "HMAC keys a hash function; only holders of the key can produce or verify the MAC.",
  },
  {
    id: "sec-13",
    category: "security",
    difficulty: "easy",
    prompt: "A VPN's primary purpose is to…",
    options: [
      "Encrypt and tunnel traffic between endpoints over an untrusted network",
      "Speed up DNS",
      "Replace TLS",
      "Filter ads",
    ],
    answer: 0,
    explanation: "A VPN creates an encrypted tunnel, often joining remote networks/users to a private network.",
  },
  {
    id: "sec-14",
    category: "security",
    difficulty: "medium",
    prompt: "AES-GCM provides…",
    options: ["Confidentiality only", "Confidentiality + integrity (AEAD)", "Hashing only", "Key exchange"],
    answer: 1,
    explanation: "GCM is an authenticated encryption mode — confidentiality and integrity in one.",
  },
  {
    id: "sec-15",
    category: "security",
    difficulty: "hard",
    prompt: "The DROWN attack abuses…",
    options: [
      "TLS 1.3",
      "Servers still supporting SSLv2 with shared keys/certs",
      "DNS recursion",
      "TCP reset injection",
    ],
    answer: 1,
    explanation: "DROWN cross-protocol-attacks any server reusing keys/cert across SSLv2 endpoints.",
  },
  {
    id: "sec-16",
    category: "security",
    difficulty: "easy",
    prompt: "RSA encryption uses…",
    options: ["A shared symmetric key", "A public key for encryption and a private key for decryption", "Hashing only", "Diffie-Hellman exclusively"],
    answer: 1,
    explanation: "RSA is asymmetric — encrypt with public, decrypt with private (and sign with private, verify with public).",
  },
  {
    id: "sec-17",
    category: "security",
    difficulty: "medium",
    prompt: "Replay attacks are mitigated by…",
    options: ["TTL", "Sequence numbers, nonces, or timestamps inside MAC'd messages", "Larger MTUs", "Caching"],
    answer: 1,
    explanation: "Including a unique nonce/sequence under the MAC means an old message won't validate twice.",
  },
  {
    id: "sec-18",
    category: "security",
    difficulty: "easy",
    prompt: "Which port does HTTPS use by default?",
    options: ["80", "443", "21", "25"],
    answer: 1,
    explanation: "HTTPS = HTTP over TLS, port 443 by default.",
  },
  {
    id: "sec-19",
    category: "security",
    difficulty: "hard",
    prompt: "Perfect Forward Secrecy in TLS 1.3 is achieved primarily via…",
    options: [
      "RSA static key exchange",
      "Ephemeral (EC)DHE key exchange",
      "Pre-shared keys only",
      "GZIP compression",
    ],
    answer: 1,
    explanation: "TLS 1.3 mandates ephemeral DH/ECDH for forward secrecy.",
  },
  {
    id: "sec-20",
    category: "security",
    difficulty: "medium",
    prompt: "A reflected DDoS amplification attack abuses…",
    options: [
      "Open services that respond to spoofed-source UDP queries with much larger replies",
      "TCP retransmits",
      "ARP caching",
      "DNS TTLs",
    ],
    answer: 0,
    explanation: "DNS, NTP, memcached etc. amplify a small spoofed query into a huge response sent to the victim.",
  },
];
